#!/usr/bin/env bash

cwd=`pwd`
cd $(dirname $0)

## watermark
if [ -f wm ]; then

  bash wm
fi

python3 compile_files.py

mkdir -p test/magicpath
mv *.pyc test/magicpath
cp -r test.py test/
cd test

python3 test.py

cd $cwd
